### ISSUE TITLE
[SF3] last update?

### ISSUE THREAD

**Issue by TheSnowyChickens** [BrainInBlack/SF-3-Tweaks#1]
Hello,

I dont know if this is the right place for it, but the curse comments are disabled and its no official issue (github) link on the page from SF3, so I google for SF3 github and find this. :)

My question is simple:
Can you create a last update for SF3? I mean Chisel and Extra Utilities 2 (and many more I think) are still updating for 1.10.2 and for example the colorless tinkers description is related to Forge (running on 2477 atm) and may its fixed with 2511. :) 

I would be very appreciated, if that were possible.
Thx

**Comment by BrainInBlack** [comment]
This is the wrong place to ask for packupdates. This project is just a set of tweaks to the original pack by BaconDonut and Darkosto. And as far as i know there are no future updates to SF3 planned, especially with SF4 development in full throttle.

You can update those mods yourself if you like, but there will be no support for modified versions on Darkostos end.

**Comment by TheSnowyChickens** [comment]
Okay, thx for the info.
